Repository dhis2/data-quality-app, pull requests merged in 2020-03, with the labels that each got.

#408 fix: remove maxDate for end-dates
  src/pages/follow-up-analysis/FollowUpAnalysis.js
  src/pages/min-max-outlier-analysis/MinMaxOutlierAnalysis.js
  src/pages/std-dev-outlier-analysis/StdDevOutlierAnalysis.js
  src/pages/validation-rules-analysis/ValidationRulesAnalysis.js
Labels: v33

#407 fix: remove maxDate for end-dates
  src/pages/follow-up-analysis/FollowUpAnalysis.js
  src/pages/min-max-outlier-analysis/MinMaxOutlierAnalysis.js
  src/pages/std-dev-outlier-analysis/StdDevOutlierAnalysis.js
  src/pages/validation-rules-analysis/ValidationRulesAnalysis.js
Labels: v32

#406 fix: remove maxDate for end-dates
  src/pages/follow-up-analysis/FollowUpAnalysis.js
  src/pages/min-max-outlier-analysis/MinMaxOutlierAnalysis.js
  src/pages/std-dev-outlier-analysis/StdDevOutlierAnalysis.js
  src/pages/validation-rules-analysis/ValidationRulesAnalysis.js
Labels: v31

#405 fix: remove maxDate for end-dates
  src/pages/follow-up-analysis/FollowUpAnalysis.js
  src/pages/min-max-outlier-analysis/MinMaxOutlierAnalysis.js
  src/pages/std-dev-outlier-analysis/StdDevOutlierAnalysis.js
  src/pages/validation-rules-analysis/ValidationRulesAnalysis.js
Labels: v30

#409 fix: remove maxDate for end-dates
  src/pages/follow-up-analysis/FollowUpAnalysis.js
  src/pages/min-max-outlier-analysis/MinMaxOutlierAnalysis.js
  src/pages/std-dev-outlier-analysis/StdDevOutlierAnalysis.js
  src/pages/validation-rules-analysis/ValidationRulesAnalysis.js
Labels: v34

#415 fix: remove maxDate for end-dates
  src/pages/follow-up-analysis/FollowUpAnalysis.js
  src/pages/min-max-outlier-analysis/MinMaxOutlierAnalysis.js
  src/pages/std-dev-outlier-analysis/StdDevOutlierAnalysis.js
  src/pages/validation-rules-analysis/ValidationRulesAnalysis.js
Labels: 2.34.0

#414 fix: content top padding
  src/App.module.css
Labels: 2.34.0

#411 fix: remove content top padding
  src/App.module.css
Labels: v34
